### ISSUE TITLE
May I request the model files, please?

### ISSUE THREAD

**Issue by ptthaothao** [autodesk-platform-services/aps-plant-operation#2]
Hello, I am working on an example with similar functionality, but I currently don't have any models. Could I request a 2D and 3D model from this repository to use as an illustration?

**Comment by yiskang** [comment]
Next time, please use https://aps.autodesk.com/get-help instead for similar inquiries.

You can download the trial version of the AutoCAD Plan3D from https://www.autodesk.com/products/autocad/included-toolsets/autocad-plant-3d .

After installing it, you can find the sample models following this instruction:
https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Where-is-the-Sample-Project-located-for-AutoCAD-Plant-3D.html
